name: Tweet Bot

on:
  schedule:
    - cron: '0 */2 * * *'  # Run every 2 hours
  workflow_dispatch:  # Allow manual trigger

# Add concurrency control
concurrency:
  group: tweet-bot
  cancel-in-progress: true

jobs:
  tweet:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Increased timeout to account for rate limit waits
    
    steps:
    - uses: actions/checkout@v3  # Updated to v3
    
    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4
      with:
        python-version: '3.10'
        cache: 'pip'  # Enable pip caching
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Add random delay
      run: |
        sleep $(( RANDOM % 300 ))  # Random delay up to 5 minutes
    
    - name: Run tweet bot
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python tweet_bot.py 
